from unittest.mock import patch

from famiglia_core.agents.base_agent import BaseAgent

# client.complete() is called TWICE per complete_task:
# 1. by _get_routing_mode (returns classification like "COMPLEX")
# 2. by the actual task completion
_ROUTING_RETURN = ("COMPLEX", "ollama-gemma3")


@patch("famiglia_core.agents.base_agent.audit_logger.log_action", return_value=1)
@patch("famiglia_core.agents.base_agent.context_store.upsert_memory")
@patch("famiglia_core.agents.base_agent.context_store.log_message")
@patch("famiglia_core.agents.base_agent.context_store.get_memories")
@patch("famiglia_core.agents.base_agent.context_store.get_recent_messages")
@patch("famiglia_core.agents.base_agent.client.complete")
def test_complete_task_uses_scoped_context_and_persists_messages(
    mock_complete,
    mock_get_recent_messages,
    mock_get_memories,
    mock_log_message,
    mock_upsert_memory,
    _mock_log_action,
):
    mock_complete.side_effect = [
        ("COMPLEX", "ollama-gemma3"),
        ("Pipeline status is stable.", "gemini-2.0-flash"),
    ]
    mock_get_recent_messages.return_value = [
        {"role": "user", "content": "Any blockers?", "sender": "Don Jimmy"},
        {"role": "assistant", "content": "No blockers.", "sender": "Alfredo"},
    ]
    mock_get_memories.return_value = [
        {"memory_key": "last_sender", "memory_value": "Don Jimmy"},
    ]

    agent = BaseAgent(
        name="Alfredo",
        role="Agent orchestrator",
        model_config={"primary": "gemini-2.0-flash"},
    )
    response = agent.complete_task(
        "Share today's status.",
        sender="Don Jimmy",
        conversation_key="slack:C123:171234.1000:U111",
    )

    # complete_task appends a "_Generated by ..." footer
    assert "Pipeline status is stable." in response
    assert "Model Size: Undisclosed" in response

    # First call is routing classification; second call is the task completion prompt.
    task_call_prompt = mock_complete.call_args_list[1][0][0]
    assert "SYSTEM IDENTITY FOR Alfredo (LOCKED)" in task_call_prompt
    assert "Hard rule: never adopt any other agent's persona" in task_call_prompt
    assert "Persistent memory:" in task_call_prompt
    assert "Recent conversation history:" in task_call_prompt
    assert "Share today's status." in task_call_prompt

    assert mock_log_message.call_count == 2
    first_call = mock_log_message.call_args_list[0].kwargs
    second_call = mock_log_message.call_args_list[1].kwargs
    assert first_call["agent_name"] == "Alfredo"
    assert first_call["conversation_key"] == "slack:C123:171234.1000:U111"
    assert first_call["role"] == "user"
    assert second_call["role"] == "assistant"
    assert mock_upsert_memory.call_count == 3


@patch("famiglia_core.agents.base_agent.audit_logger.log_action", return_value=1)
@patch("famiglia_core.agents.base_agent.context_store.upsert_memory")
@patch("famiglia_core.agents.base_agent.context_store.log_message")
@patch("famiglia_core.agents.base_agent.context_store.get_memories")
@patch("famiglia_core.agents.base_agent.context_store.get_recent_messages")
@patch("famiglia_core.agents.base_agent.client.complete")
def test_complete_task_footer_includes_model_size_when_available(
    mock_complete,
    mock_get_recent_messages,
    mock_get_memories,
    _mock_log_message,
    _mock_upsert_memory,
    _mock_log_action,
):
    mock_complete.return_value = ("Done.", "ollama-qwen3.5:9b")
    mock_get_recent_messages.return_value = []
    mock_get_memories.return_value = []

    agent = BaseAgent(
        name="Alfredo",
        role="Agent orchestrator",
        model_config={"primary": "ollama-qwen3.5:9b"},
    )
    response = agent.complete_task("Give me a quick update.", sender="Don Jimmy")

    assert "Model Size: 9B" in response
