import sys
import os
from unittest.mock import MagicMock, patch

# Add src to path
sys.path.append(os.getcwd())

from famiglia_core.agents.rossini import Rossini
from famiglia_core.agents.llm.client import client

def test_rossini_model_selection():
    rossini = Rossini()
    
    # Mock the LLM client.complete to see what's being called
    with patch.object(client, 'complete', return_value=("Mock response", "mock-model")) as mock_complete:
        # 1. Test CHAT mode (should use secondary)
        print("Testing CHAT mode...")
        rossini.complete_task("Hi Rossini", sender="Jimmy")
        
        # Check first call (routing)
        # BaseAgent uses fallback_model for routing
        # fallback_model = secondary or global_fallback
        routing_call = mock_complete.call_args_list[0]
        routing_model = routing_call[0][1]['primary']
        print(f"Routing model used: {routing_model}")
        
        # Check second call (actual completion)
        completion_call = mock_complete.call_args_list[1]
        completion_model = completion_call[0][1]['primary']
        print(f"Completion model used: {completion_model}")
        
        expected_secondary = rossini.model_config.get("secondary")
        if routing_model == expected_secondary and completion_model == expected_secondary:
            print("SUCCESS: Rossini used secondary model for CHAT.")
        else:
            print(f"FAILURE: Rossini used {completion_model} instead of {expected_secondary}.")

        mock_complete.reset_mock()

        # 2. Test SEARCH mode (should hit keyword fast-path)
        print("\nTesting SEARCH mode (web search keyword)...")
        rossini.complete_task("search for current market trends", sender="Jimmy")
        
        # With keyword fast-path, the routing LLM call is SKIPPED.
        # So there should only be ONE call total (the completion call).
        call_count = mock_complete.call_count
        print(f"Total LLM calls: {call_count}")
        
        # Completion call
        completion_call = mock_complete.call_args_list[0]
        completion_model = completion_call[0][1]['primary']
        print(f"Completion model used: {completion_model}")
        
        if call_count == 1 and completion_model == expected_secondary:
            print("SUCCESS: Rossini used secondary model for SEARCH via Fast-Path.")
        else:
            print(f"FAILURE: Rossini used {completion_model} with {call_count} calls.")

        mock_complete.reset_mock()

        # 3. Test Keyword Fast-Path (No LLM call for routing)
        print("\nTesting Keyword Fast-Path (web search)...")
        rossini.complete_task("perform a simple web search", sender="Jimmy")
        
        # Check that only ONE call was made (the completion call, not the routing call)
        # Because the keyword fast-path should skip the routing LLM call.
        call_count = mock_complete.call_count
        print(f"Total LLM calls: {call_count}")
        if call_count == 1:
            print("SUCCESS: Keyword Fast-Path skipped routing LLM call.")
        else:
            print(f"FAILURE: Routing LLM call was not skipped (Calls: {call_count}).")

        mock_complete.reset_mock()

        # 4. Test Robust Fallback on LLM Failure
        print("\nTesting Robust Fallback on LLM Failure...")
        with patch.object(client, 'complete', side_effect=[Exception("Ollama Down"), ("Mock response", "fallback-model")]) as mock_fail_complete:
            # We use a prompt that is COMPLEX but doesn't hit keywords
            # "strategy for the family business" -> should hit LLM but LLM fails
            response = rossini.complete_task("strategy for the family business", sender="Jimmy")
            
            # The code should catch the exception, print it, and default to CHAT (or COMPLEX if keywords match)
            # In this case "strategy" is in complex_keywords
            print(f"Agent response contains fallback indicator: {'_Generated by' in response}")
            
            # Verify the second call still happened (for completion)
            if mock_fail_complete.call_count >= 1:
                print("SUCCESS: Agent proceeded to completion even after routing failure.")
            else:
                print("FAILURE: Agent stopped after routing failure.")

if __name__ == "__main__":
    test_rossini_model_selection()
