import os
import re
from typing import Optional, TYPE_CHECKING, List

if TYPE_CHECKING:
    from famiglia_core.agents.base_agent import BaseAgent

from famiglia_core.agents.tools.notion import notion_client
from famiglia_core.agents.tools.github import github_client
from famiglia_core.command_center.backend.comms.slack.client import slack_queue, PRIORITY_MEDIUM


class Workflows:
    """Reusable workflows for agents."""

    def test_notion_page_creation(self: "BaseAgent", parent_page_id: str, title: str = "Test Page", user_prompt: Optional[str] = None, thread_ts: Optional[str] = None) -> str:
        """Create a test Notion page, append placeholder text to it, and report success automatically."""
        # Default to the Weekly Researches page if the ID is missing or just the page name itself
        if not parent_page_id or parent_page_id.lower() in ["weekly researches", "research", "weekly-researches"]:
            parent_page_id = "31ff5d41fe97808d9530f49bff903f92"

        if self.propose_action(f"Running Notion Test Workflow under parent {parent_page_id}"):
            print(f"[{self.name}] Workflow Start: Notion Page Creation")
            try:
                # 1. create_notion_page
                print(f"[{self.name}] Step 1/2: Creating Notion page...")
                create_result = notion_client.create_page(parent_page_id, title, "Initial Test Creation", agent_name=self.name)
                print(f"[{self.name}] Step 1/2: Complete. Result: {create_result}")
                
                # Try to loosely extract the new page ID from the result string. 
                match = re.search(r"ID:\s*([^\s.]+)", create_result)
                new_page_id = match.group(1) if match else None

                # 2. write_notion_page
                if new_page_id:
                    print(f"[{self.name}] Step 2/2: Appending text to page {new_page_id}...")
                    notion_client.append_text_to_page(new_page_id, "This is placeholder test text generated by the agent's test workflow.", agent_name=self.name)
                    print(f"[{self.name}] Step 2/2: Complete.")
                
                # 3 & 4. Confirm and report
                final_report = f"Test Workflow Complete. {create_result}"
                if new_page_id:
                    final_report += f" Successfully appended placeholder text to the new page ({new_page_id})."
                
                # Send explicit slack notification since this bypasses the standard multi-turn workflow
                final_thread_ts = thread_ts or getattr(self, "current_thread_ts", None)
                slack_queue.enqueue_message(
                    agent=self.agent_id,
                    channel=os.getenv("DEV_CHANNEL_ID", "system"),
                    message=f"🎩 Testing workflow completed successfully:\n{final_report}",
                    priority=PRIORITY_MEDIUM,
                    thread_ts=final_thread_ts
                )
                    
                print(f"[{self.name}] Workflow Complete: Notion Page Creation")
                return final_report
            except Exception as e:
                return f"Failed during Notion Test Workflow: {e}"

        return "Workflow cancelled or action declined."

    def test_github_diagnostic(self: "BaseAgent", repo_name: str = "852-Lab/jimwurst", issue_number: int = 1, user_prompt: Optional[str] = None, thread_ts: Optional[str] = None) -> str:
        """Primary user-facing diagnostic: check token and repo access. Preferred ONLY for general integrity/connection testing."""
        if self.propose_action(f"Running Full GitHub Diagnostic on {repo_name}"):
            print(f"[{self.name}] Workflow Start: GitHub Diagnostic")
            try:
                final_thread_ts = thread_ts or getattr(self, "current_thread_ts", None)
                results = []

                # Step 1: Token
                print(f"[{self.name}] Step 1/3: Generating GitHub App Token...")
                github_client._get_app_token(self.name)
                print(f"[{self.name}] Step 1/3: Complete.")
                msg1 = "🩺 *GitHub Diagnostic (Step 1/3):* Token generated successfully."
                slack_queue.enqueue_message(
                    agent=self.agent_id,
                    channel=os.getenv("DEV_CHANNEL_ID", "system"),
                    message=msg1,
                    priority=PRIORITY_MEDIUM,
                    thread_ts=final_thread_ts
                )
                results.append(msg1)

                # Step 2: List Repos
                print(f"[{self.name}] Step 2/3: Listing accessible repositories...")
                repos = github_client.list_accessible_repos(self.name)
                print(f"[{self.name}] Step 2/3: Complete. Found {len(repos)} repos.")
                repo_names = [str(r.get("full_name")) for r in repos]
                display_names = [repo_names[i] for i in range(min(3, len(repo_names)))]
                msg2 = f"🩺 *GitHub Diagnostic (Step 2/3):* Found {len(repos)} accessible repositorie(s): {', '.join(display_names)}..."
                slack_queue.enqueue_message(
                    agent=self.agent_id,
                    channel=os.getenv("DEV_CHANNEL_ID", "system"),
                    message=msg2,
                    priority=PRIORITY_MEDIUM,
                    thread_ts=final_thread_ts
                )
                results.append(msg2)

                # Step 3: List Issues for ALL repositories
                print(f"[{self.name}] Step 3/3: Listing issues for all accessible repositories...")
                all_issues_summary = []
                total_repos = len(repo_names)
                
                for i, r_name in enumerate(repo_names):
                    try:
                        print(f"[{self.name}] Step 3/3: Checking {r_name} ({i+1}/{total_repos})...")
                        issues = github_client.list_issues(r_name, self.name)
                        count = len(issues)
                        print(f"[{self.name}] Step 3/3: Found {count} issue(s) in {r_name}.")
                        all_issues_summary.append(f"• {r_name}: {count} open issue(s)")
                    except Exception as repo_err:
                        print(f"[{self.name}] Step 3/3: Error checking {r_name}: {repo_err}")
                        all_issues_summary.append(f"• {r_name}: ⚠️ Error (Possible 404 or permission issue)")

                issues_text = "\n".join(all_issues_summary)
                msg3 = f"🩺 *GitHub Diagnostic (Step 3/3):* Issue report for all repos:\n{issues_text}\n\nDiagnostic Complete."
                
                slack_queue.enqueue_message(
                    agent=self.agent_id,
                    channel=os.getenv("DEV_CHANNEL_ID", "system"),
                    message=msg3,
                    priority=PRIORITY_MEDIUM,
                    thread_ts=final_thread_ts
                )
                results.append(msg3)
                print(f"[{self.name}] Workflow Complete: GitHub Diagnostic")
                return "\n".join(results)

            except Exception as e:
                return f"Failed during GitHub Diagnostic Workflow: {e}"
        
        return "Workflow cancelled or action declined."
