/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f1f",
        "secondary": "#c8c6c5",
        "on-tertiary-container": "#4f3e00",
        "on-primary": "#680018",
        "surface-container-high": "#2a2a2a",
        "on-secondary-container": "#b7b5b4",
        "outline-variant": "#554240",
        "primary": "#ffb3b5",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#c8c6c5",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed": "#1c1b1b",
        "surface-container-low": "#1c1b1b",
        "background": "#131313",
        "surface-container-highest": "#353534",
        "on-background": "#e5e2e1",
        "surface-tint": "#ffb3b5",
        "on-surface-variant": "#dcc0bd",
        "on-secondary-fixed-variant": "#474746",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#574500",
        "surface-dim": "#131313",
        "surface": "#131313",
        "tertiary-fixed-dim": "#e9c349",
        "on-primary-fixed-variant": "#8e0f28",
        "on-primary-fixed": "#40000b",
        "on-tertiary-fixed": "#241a00",
        "surface-variant": "#353534",
        "inverse-primary": "#af2b3e",
        "inverse-on-surface": "#313030",
        "primary-container": "#4c000f",
        "secondary-container": "#474746",
        "outline": "#a38b88",
        "on-tertiary": "#3c2f00",
        "tertiary": "#eac34a",
        "on-secondary": "#313030",
        "primary-fixed-dim": "#ffb3b5",
        "surface-bright": "#393939",
        "secondary-fixed": "#e5e2e1",
        "primary-fixed": "#ffdada",
        "on-primary-container": "#e95665",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffe088",
        "inverse-surface": "#e5e2e1",
        "tertiary-container": "#cca830",
        "on-error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Noto Serif"],
        "body": ["Manrope"],
        "label": ["Space Grotesk"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
